// apps/reveal-svelte/src/routes/components/Announcer.svelte
<script module lang="ts">
	import { goto } from '$app/navigation';

	let announcerState = $state<'wait' | 'left' | 'right'>('left');
	let isLeft = $state(true);

	const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

	export async function announce(url: string) {
		announcerState = 'wait';
		await sleep(800);

		announcerState = isLeft ? 'right' : 'left';
		isLeft = !isLeft;

		await goto(url);
	}
</script>

<div id="navigation-announcer" data-nav-state={announcerState}></div>

<style>
	#navigation-announcer {
		position: fixed;
		width: 100%;
		height: 100%;
		background: black;
		top: 0;
		left: -100%;
		transform-origin: left;
		transition: 400ms ease-in-out;
		cursor: wait;
	}

	#navigation-announcer[data-nav-state='wait'] {
		left: 0%;
	}

	#navigation-announcer[data-nav-state='left'] {
		left: -100%;
	}

	#navigation-announcer[data-nav-state='right'] {
		left: 100%;
	}
</style>

// apps/reveal-react/src/components/Announcer.tsx
"use client";

import { useRouter } from "next/navigation";
import { PropsWithChildren, useCallback } from "react";
import { useAnnouncerContext } from "./AnnouncerContext";

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

export default function Announcer({ children }: PropsWithChildren) {
  const { status } = useAnnouncerContext();

  return (
    <>
      <div id="navigation-announcer" data-nav-state={status.state}></div>
      {children}
    </>
  );
}

export function useAnnouncer() {
  const { setStatus } = useAnnouncerContext();
  const router = useRouter();

  return useCallback(
    async (url: string) => {
      setStatus((prev) => ({ ...prev, state: "wait" }));
      await sleep(800);

      setStatus((prev) => {
        return {
          isLeft: !prev.isLeft,
          state: prev.isLeft ? "right" : "left",
        };
      });

      router.push(url);
    },
    [router],
  );
}
